### ISSUE TITLE
Map isn't the last moments before whiteout

### ISSUE THREAD

**Issue by skellitor301** [RolandR/place-atlas#37]
Hi there, I wanted to share what I could about the most last bits of r/Place before the whiteout started. I've scoured as much as I could and this is the lastest one I could find: https://rplace.space/combined/1649112455.png

Mostly making this post to maintain accuracy for r/place to be the most complete

**Comment by dark-swordsman** [comment]
I came here to mention this too, since I made something with a group that pretty much only appears in the last hour.

I guess what would be cool as a long term project, maybe, is to include a timeline with variants. I know people have created timelapses, and I refuse to believe that they don't have the source frames over a period of time for the whole thing.

I.E: The coordinates and details can remain, but they can be dynamic and change based upon the state of a map at a period of time. It would be a much more interactive experience and probably multiply the effect of this app further.

**Comment by skellitor301** [comment]
So I did find a newer version to the one that is currently being used on the site. It unfortunately isn't the most last version out there, the first link is the one I can say is due to actively working on the TotalBiscuit memorial at the time, last bit of work was on the left side of the name, the left border was brought all the way to the irish flag and I was about to start working on stopping the flag at the border, until the whiteout began. This one at the very least is much closer and is of much better quality than the initial link, hopefully we can find one of the same quality as this one but at the furthest state
https://i.redd.it/ex9g0dctplr81.png

**Comment by skellitor301** [comment]
I just now realized this is the old r/place atlas and not the new one. Sorry about that. I'll reference this issue to the new atlas github.
